### ISSUE TITLE
Documentation has error

### ISSUE THREAD

**Issue by qwertyad1** [jacobschwantes/eight-ball-api#1]
The /biased example, in the docs, shows: 
`https://eightballapi.com/api/biased?q=Will+I+win+the+lottery?` 
proper syntax would be:
 `https://eightballapi.com/api/biased?question=Will+I+win+the+lottery?`

**Comment by jacobschwantes** [comment]
Hi @qwertykid,

Thank you for opening this issue and bringing it to my attention. I have implemented a fix for this problem in commit bed9bfeb6fabd6639363041a0d7d9752bc1ae49e: fix incorrect query params.

I will be closing this issue now as it has been resolved. If you have any further concerns or find any other issues, please feel free to open a new issue or reach out to me directly.

Best regards,
Jacob
